name: Send Daily Reminder

on:
  schedule:
    - cron: '30 14 * * 1-5'  # 17:30 по Москве = 14:30 UTC
  workflow_dispatch:         # для ручного запуска

jobs:
  send-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run BIC bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bic_bot.py
